 spring:
   security:
     oauth2:
       client:
         registration:
           keycloak:
             client-id: jdbc-query-dsl
             client-secret: kd9N8LwO8UZUH3BkrRJCxBzN2bGEy2xA
             scope: openid
             authorization-grant-type: authorization_code
             redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
         provider:
           keycloak:
             issuer-uri: http://localhost:8080/realms/wizlit-dev

 server:
   port: 1010